### ISSUE TITLE
Seperate out kinematics and matrix code from astar code

### ISSUE THREAD

**Issue by Boberito25** [Boberito25/ButlerBot#1]
Generally I would like to keep functionalities as distinct as possible. At the very least it would be good to know why they are in the same file.  I've pushed some new code because I had merge conflicts.

**Comment by zng** [comment]
I thought we would end up with cyclic dependancies if they were in different files. The FK would have to know about the astar types, and the astar would need the FK functions in the hueristic function and such. Maybe that is fine. I was just worried.

**Comment by Boberito25** [comment]
mk I want to see if we can design around this some how...lets talk at some point cause u might be right
